# Generated by Django 2.2.23 on 2021-06-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name_katakana',
        ),
    ]
